config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'menu#index', as: 'home'
  get 'statistics' => 'statistics#statistics', as: 'statistics'
  get 'new' => 'products#new', as: 'new'
  resources :menu
  resources :products
  resources :suppliers
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :products, through: :orderpositions
end

app/models/orderposition.rb
class Orderposition < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, through: :orderpositions
  validates :Bezeichnung, presence: true,
                            length: {minimum: 3}
  # scope :starts_with, -> (name) { where("name like ?", "#{name}%")}

  def self.search(search_term)
    where("Bezeichnung like :search_term", search_term: "%#{search_term}%")
  end

  def self.search_by(search_term)
    where("LOWER(Bezeichnung) LIKE :search_term", search_term: "%#{search_term}%")
  end
end
#"%#{search_term}%")

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  def self.search(search_term)
    where("Name like :search_term", search_term: "%#{search_term}%")
  end

  def self.search_by(search_term)
    where("LOWER(Name) LIKE :search_term", search_term: "%#{search_term}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]
  def index

    # @products = Product.search(params[:search_product],params[:search_al])
    @products = Product.all
    @products = Product.search(params[:search].to_param) unless params[:search].blank?
    # if params[:search]
    #   @search_term = params[:search]
    #   @products = @products.search_by(@search_term)
    # else params[:search] ==
    #   @products = Product.all
    # end
  end
  def new
    @stuff = Product.new
  end

  def create
    #render plain: params[:stuff].inspect
    # @supplier = Supplier.find(params[:id])
    @stuff = Product.new(product_params)

    if(@stuff.save)
    redirect_to @stuff
    else
      render 'new'
    end

  end

  def show
    @stuff = Product.find(params[:id])
  end

  def edit
    @stuff = Product.find(params[:id])
  end

  def update
    @stuff = Product.find(params[:id])

    if(@stuff.update(product_params))
      redirect_to @stuff
    else
      render 'edit'
    end
  end

  def destroy
    @stuff = Product.find(params[:id])
    @stuff.destroy

    redirect_to products_path
  end

  private def product_params

    params.require(:stuff).permit(:Artikelnummer, :Bezeichnung, :Preis, :EK, :Bestand, :Bestellt, :Marke, :Lieferant)
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def statistics
    @title = 'Statistics Overview'
    @content = 'Here are some statistics'
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]
  def index
    @suppliers = Supplier.all
    @suppliers = Supplier.search(params[:search].to_param) unless params[:search].blank?
  end

  def new
    @supplierinfo = Supplier.new
  end

  def create
    #render plain: params[:supplierinfo].inspect
    @supplierinfo = Supplier.new(supplier_params)

    if(@supplierinfo.save)
      redirect_to @supplierinfo
    else
      render 'new'
    end

  end

  def show
    @supplierinfo = Supplier.find(params[:id])
  end

  def edit
    @supplierinfo = Supplier.find(params[:id])
  end

  def update
    @supplierinfo = Supplier.find(params[:id])

    if(@supplierinfo.update(product_params))
      redirect_to @supplierinfo
    else
      render 'edit'
    end
  end

  def destroy
    @supplierinfo = Supplier.find(params[:id])
    @supplierinfo.destroy

    redirect_to suppliers_path
  end

  private def supplier_params
    params.require(:supplierinfo).permit(:Lieferantennummer, :Name, :Adresse, :Telefonnummer, :Email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supermarkt</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#   gem 'coffee-script-source', '1.8.0'    %>
    <%#   bundle update coffee-script-source     %>

  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" <%= link_to "Home", home_path %> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Sortiment", products_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Lieferanten", suppliers_path %></a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" <%#= link_to "Bestellungen", orders_path %></a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" <%#= link_to "Statistiken", statistics_path %></a>-->
<!--        </li>-->
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <a class="navbar-brand" <%= link_to "Super-SEA-Supermarkt", home_path %></a>
      </form>
    </div>
  </nav>
  </div>

<div class="container">
  <%= yield %>
</div>

  </body>
</html>

app/views/menu/index.html.erb
<h1>Hallo Mitarbeiter!</h1>
<hr>
<%= image_tag("market.jpg", class: "img-responsive center-block") %>

app/views/orders/index.html.erb
<h1>Hier könnte eine Auflistung von Bestellungen stehen...</h1>

app/views/products/edit.html.erb
<h1>Produkt hinzufügen</h1>
<%= form_for :stuff, url: product_path(@stuff), method: :patch do |f| %>
  <% if @stuff.errors.any? %>
    <% @stuff.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :Artikelnummer %><br>
    <%= f.text_field(:Artikelnummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Bezeichnung %><br>
    <%= f.text_field(:Bezeichnung, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Preis %><br>
    <%= f.text_field(:Preis, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :EK %><br>
    <%= f.text_field(:EK, {:class => 'form-control'}) %>
  </p>

<!--  <p>-->
<!--    <%#= f.label :Bestand %><br>-->
    <%#= f.text_field(:Bestand, {:class => 'form-control'}) %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :Bestellt %><br>-->
    <%#= f.text_field(:Bestellt, {:class => 'form-control'}) %>
<!--  </p>-->

  <p>
    <%= f.label :Marke %><br>
    <%= f.text_field(:Marke, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Lieferant %><br>
    <%= f.select(:Lieferant, options_from_collection_for_select(Supplier.all, :Name, :Name), {}, :class => 'form-control') %>
  </p>

  <p>
    <%= f.submit(:Ändern, {:class => 'btn btn-primary'}) %>
  </p>
<% end %>
<%= link_to "Löschen", product_path(@stuff),
            method: :delete,
            data: {confirm: 'Sicher?'},
            :class => 'btn btn-danger' %>

app/views/products/index.html.erb
<h1>Sortiment</h1>
<div class="form-group">
  <%= form_for "", url:products_path , role: "search", method: :get do %>
    <%= text_field :search, @search_term, placeholder: " Search.." %>
  <% end %>
</div>
<div class="form-group">
  <a class="btn btn-primary" <%= link_to "Neues Produkt", new_product_path %></a>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Artikelnummer</th>
    <th scope="col">Bezeichnung</th>
    <th scope="col">Preis</th>
    <th scope="col">EK</th>
    <th scope="col">Lieferant</th>
    <th scope="col">Marke</th>
<!--    <th scope="col">Bestand</th>-->
<!--    <th scope="col">Bestellt</th>-->
  </tr>
  </thead>
  <tbody>
  <% @products.each_with_index do |product, i| %>
    <tr>
      <th scope="row"><%= i + 1 %></th>
      <td><%= product.Artikelnummer %></td>
      <td><%= product.Bezeichnung %></td>
      <td><%= product.Preis %> €</td>
      <td><%= product.EK %> €</td>
      <td><%= product.Lieferant %></td>
      <td><%= product.Marke %></td>
<!--      <td><%#= product.Bestand %></td>-->
<!--      <td><%#= product.Bestellt %></td>-->
      <td><%= link_to "Bearbeiten", edit_product_path(product), :class => 'btn btn-default' %></td>
    </tr>
  <% end %>
    </tbody>
  </table>

app/views/products/new.html.erb
<h1>Produkt hinzufügen</h1>
<%= form_for :stuff, url: products_path do |f| %>
  <% if @stuff.errors.any? %>
    <% @stuff.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :Artikelnummer %><br>
    <%= f.text_field(:Artikelnummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Bezeichnung %><br>
    <%= f.text_field(:Bezeichnung, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Preis %><br>
    <%= f.text_field(:Preis, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :EK %><br>
    <%= f.text_field(:EK, {:class => 'form-control'}) %>
  </p>

<!--  <p>-->
<!--    <%#= f.label :Bestand %><br>-->
    <%#= f.text_field(:Bestand, {:class => 'form-control'}) %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :Bestellt %><br>-->
    <%#= f.text_field(:Bestellt, {:class => 'form-control'}) %>
<!--  </p>-->

  <p>
    <%= f.label :Marke %><br>
    <%= f.text_field(:Marke, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Lieferant %><br>
    <%= f.select(:Lieferant, options_from_collection_for_select(Supplier.all, :Name, :Name), {}, :class => 'form-control') %>
  </p>

  <p>
    <%= f.submit(:Hinzufügen, {:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/products/show.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">Artikelnummer</th>
    <th scope="col">Bezeichnung</th>
    <th scope="col">Preis</th>
    <th scope="col">EK</th>
    <th scope="col">Lieferant</th>
    <th scope="col">Marke</th>
<!--    <th scope="col">Bestand</th>-->
<!--    <th scope="col">Bestellt</th>-->
  </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @stuff.Artikelnummer %></td>
      <td><%= @stuff.Bezeichnung %></td>
      <td><%= @stuff.Preis %> €</td>
      <td><%= @stuff.EK %> €</td>
      <td><%= @stuff.Lieferant %></td>
      <td><%= @stuff.Marke %></td>
<!--      <td><%#= @stuff.Bestand %></td>-->
<!--      <td><%#= @stuff.Bestellt %></td>-->
    </tr>
  </tbody>
</table>
<hr>
<%= link_to "Bearbeiten", edit_product_path(@stuff), :class => 'btn btn-default' %>
<%= link_to "Löschen", product_path(@stuff),
            method: :delete,
            data: {confirm: 'Sicher?'},
            :class => 'btn btn-danger' %>

app/views/statistics/statistics.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/suppliers/edit.html.erb
<h1>Lieferant ändern</h1>
<%= form_for :supllierinfo, url: suppliers_path do |f| %>
  <%# if @supllierinfo.errors.any? %>
  <%# @supllierinfo.errors.full_messages.each do |msg| %>
  <!--      <div class="alert alert-danger"><%#= msg %></div>-->
  <%# end %>
  <%# end %>
  <p>
    <%= f.label :Lieferantennummer %><br>
    <%= f.text_field(:Lieferantennummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field(:Name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Adresse %><br>
    <%= f.text_field(:Adresse, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Telefonnummer %><br>
    <%= f.text_field(:Telefonnummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.text_field(:Email, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit(:Ändern, {:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/suppliers/index.html.erb
<h1>Lieferanten</h1>
<div class="form-group">
  <%= form_for "", url:suppliers_path , role: "search", method: :get do %>
    <%= text_field :search, @search_term, placeholder: " Search.." %>
  <% end %>
</div>
<div class="form-group">
  <a class="btn btn-primary" <%= link_to "Neuer Lieferant", new_supplier_path %></a>
</div>
<table id="prducts", class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Lieferantennummer</th>
    <th scope="col">Name</th>
    <th scope="col">Adresse</th>
    <th scope="col">Telefonnummer</th>
    <th scope="col">Email</th>
  </tr>
  </thead>
  <tbody>
  <% @suppliers.each_with_index do |supplier, i| %>
    <tr>
      <th scope="row"><%= i + 1 %></th>
      <td><%= supplier.Lieferantennummer %></td>
      <td><%= supplier.Name %></td>
      <td><%= supplier.Adresse %></td>
      <td><%= supplier.Telefonnummer %></td>
      <td><%= supplier.Email %></td>
      <td><%= link_to "Bearbeiten", edit_supplier_path(supplier), :class => 'btn btn-default' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/suppliers/new.html.erb
<h1>Lieferant ändern</h1>
<%= form_for :supplierinfo, url: suppliers_path do |f| %>
  <%# if @supllierinfo.errors.any? %>
    <%# @supllierinfo.errors.full_messages.each do |msg| %>
<!--      <div class="alert alert-danger"><%#= msg %></div>-->
      <%# end %>
    <%# end %>
  <p>
    <%= f.label :Lieferantennummer %><br>
    <%= f.text_field(:Lieferantennummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field(:Name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Adresse %><br>
    <%= f.text_field(:Adresse, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Telefonnummer %><br>
    <%= f.text_field(:Telefonnummer, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.text_field(:Email, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit(:Hinzufügen, {:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/suppliers/show.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">Lieferantennummer</th>
    <th scope="col">Name</th>
    <th scope="col">Adresse</th>
    <th scope="col">Telefonnummer</th>
    <th scope="col">Email</th>
  </tr>
  </thead>
  <tbody>

    <tr>
      <td><%= @supplierinfo.id %></td>
      <td><%= @supplierinfo.Lieferantennummer %></td>
      <td><%= @supplierinfo.Name %></td>
      <td><%= @supplierinfo.Adresse %> </td>
      <td><%= @supplierinfo.Telefonnummer %> €</td>
      <td><%= @supplierinfo.Email %></td>
    </tr>
  </tbody>
</table>
<%= link_to "Bearbeiten", edit_supplier_path(@supplierinfo), :class => 'btn btn-default' %>
<%= link_to "Löschen", supplier_path(@supplierinfo),
            method: :delete,
            data: {confirm: 'Sicher?'},
            :class => 'btn btn-danger' %>